app/views/auth.py
import os
from dotenv import load_dotenv, find_dotenv, set_key

from flask import Blueprint, render_template, redirect, url_for, request, flash
from flask_login import login_user, logout_user, login_required, current_user
from flask_bcrypt import check_password_hash, generate_password_hash

from ..models.auth_info import PermissionLevel
from ..models.db_manager import db_manager
from ..models.user import User

auth = Blueprint('auth', __name__, url_prefix='/')

def set_master_administrator(email, password):
    try:
        dotenv_file = find_dotenv()
        load_dotenv(dotenv_file, override=True)
        if (email != os.environ['MASTER_ADMIN_MAIL']) | (password != os.environ['MASTER_ADMIN_PASSWORD']):
            return

        master_administrator = User.query.filter_by(email=email).first()
        if master_administrator:
            return

        name = 'master administrator'
        master_administrator = User(email=email, name=name, password=generate_password_hash(password), permission=PermissionLevel.MASTER_ADMIN)
        is_success = db_manager.add_user(master_administrator)
        if is_success:
            set_key(dotenv_file, 'MASTER_ADMIN_MAIL', '')
            set_key(dotenv_file, 'MASTER_ADMIN_PASSWORD', '')
        else:
            pass # If registing to db was failed, the master administrator info leaves .env file.
    except Exception:
        pass # If occuring unexpected exceptions in this function, do nothing(return None).

    return

@login_required
@auth.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.permission != PermissionLevel.MASTER_ADMIN:
        return redirect(url_for('auth.login')), 403

    if request.method == 'POST':
        try:
            email = request.form.get('email')
            name = request.form.get('name')
            password = request.form.get('password')

            user = User.query.filter_by(email=email).first()
            if user:
                return redirect(url_for('auth.register'))

            new_user = User(email=email, name=name, password=generate_password_hash(password), permission=PermissionLevel.USER)
            is_success = db_manager.add_user(new_user)

            if is_success:
                return redirect(url_for('auth.login'))
            else:
                return redirect(url_for('auth.register'))
        except Exception:
            return redirect(url_for('auth.register'))
    else:
        return render_template('registration.html')

@auth.route('/login', methods=['GET', 'POST'])
def login():
    try:
        if request.method == 'POST':
            email = request.form.get('email')
            password = request.form.get('password')
            remember = True if request.form.get('remember') else False

            set_master_administrator(email, password)
            user = User.query.filter_by(email=email).first()
            if not user:
                flash('Please check your login details and try again.')
                return redirect(url_for('auth.login', is_authenticated=False))

            if not check_password_hash(user.password, password):
                flash('Please check your login details and try again.')
                return redirect(url_for('auth.login', is_authenticated=False))

            login_user(user, remember=remember)
            return redirect(url_for('main.index'))
        else:
            if current_user.is_authenticated:
                return redirect(url_for('main.index', is_authenticated=True))
            else:
                return render_template('login.html')
    except Exception:
        return redirect(url_for('auth.login', is_authenticated=False))

@auth.route('/logout')
@login_required
def logout():
    try:
        logout_user()
    except Exception:
        pass
    return redirect(url_for('auth.login'))

app/views/editor.py
import os
from flask import current_app, Blueprint, render_template, redirect, url_for, request, flash, jsonify
from flask_login import login_required, current_user
from werkzeug.utils import secure_filename

ALLOWING_EXTENSIONS = set(['mp4'])
def is_file_allowed(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWING_EXTENSIONS

editor = Blueprint('editor', __name__, url_prefix='/')

@editor.route('/editor', methods=["GET"])
@login_required
def edit_mp4():
    return render_template('video_editor.html', name=current_user.name), 200

@editor.route('/upload', methods=['GET', 'POST'])
@login_required
def upload_file():
    if request.method == 'POST':
        response_code = 500
        response_dict = {}
        try:
            if 'file' not in request.files:
                flash('Any file is not found.')
                response_code = 400
                response_dict['message'] = 'Any file is not found.'
                raise({'code': 400, 'dict': {'message': 'Any file is not found.'}})

            flash('A file is found.')
            file = request.files['file']
            if file.filename == '':
                flash('The name of uploaded file is invalid.')
                raise({'code': 400, 'dict': {'message': 'The name of uploaded file is invalid.'}})

            flash('The name of uploaded file is valid.')
            if not is_file_allowed(file.filename):
                flash('The extension of uploaded file is invalid.')
                raise({'code': 400, 'dict': {'message': 'The extension of uploaded file is invalid.'}})

            flash('The extension of uploaded file is valid.')
            filename = secure_filename(file.filename)
            file.save(os.path.join(current_app.config['UPLOAD_FOLDER'], filename))
            response_code = 200
            response_dict = {'message': 'Uploading file is completed.'}
        except Exception as e:
            if hasattr(e, 'keys'):
                response_code = e['code'] if 'code' in e.keys() else 500
                response_dict = e['dict'] if 'dict' in e.keys() else {'message': 'Internal server error.'}
            else:
                response_code = 500
                response_dict = {'message': 'Internal server error.'}

        return jsonify(response_dict), response_code

    else:
        return redirect(url_for('editor.edit_mp4'))

app/templates/index.html
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Main</title>
  </head>
  <body>
    <div style="text-align:right;">
      <p>{{name}}</p>
      <button onclick="window.location.href='{{url_for('auth.logout')}}';">Log out</button>
    </div>
    <div>
      <p>This is the main page.</p>
    </div>
    <script>
    </script>
  </body>
</html>

app/templates/login.html
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
  </head>
  <body>
    <div style="margin: 5px;">
      <form action="javascript:login()">
        <div><span>E-Mail : </span><input type="text" id="email" /></div>
        <div><span>Password : </span><input type="password" id="password" /></div>
        <div><button id="loginBtn">Log in</button></div>
      </form>
      <!--<div><a href="" style="margin: 5px;">Forgot password.</a></div>-->
    </div>
    <script>
      const email = document.getElementById('email');
      const password = document.getElementById('password');
      const loginBtn  = document.getElementById('loginBtn');

      function login() {
        if ((email.value !== '') && (password.value !== '')) {
          let fData = new FormData();
          fData.append('email', email.value);
          fData.append('password', password.value);
          
          fetch("{{url_for('auth.login')}}", {
            method: 'POST',
            headers: {},
            body: fData
          }).then(response => {
            const url = new URL(response.url);
            const is_auth = url.searchParams.get('is_authenticated');
            if (is_auth === 'False') {
              alert('Authentication is failed, incorrect username or password.', 'Authentication is failed!');
            }
            else {
              window.location.href = window.location.href;
            }
          }).catch(error => {
            alert('Occuring some error on login process.', 'Error is happen!');
          });
        }
        else {
          alert('Please input E-Mail address and password.', 'Caution!');
        }
      }
    </script>
  </body>
</html>

app/templates/registration.html
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User Registration</title>
  </head>
  <body>
    <div style="margin: 5px;">
      <form action="javascript:register()">
        <div><span>E-Mail : </span><input type="email" id="email" /></div>
        <div><span>name : </span><input type="text" id="name" /></div>
        <div><span>Password : </span><input type="password" id="password" /></div>
        <div><span>Confirm Password : </span><input type="password" id="confirm" /></div>
        <div><button id="registBtn">Registration</button></div>
      </form>
      <button onclick="window.location.href='{{url_for('auth.login')}}';">Move to the login page</button>
    </div>
    <script>
      const email = document.getElementById('email');
      const name = document.getElementById('name');
      const password = document.getElementById('password');
      const confirm = document.getElementById('confirm');
      const registBtn  = document.getElementById('registBtn');

      function register() {
        if ((email.value === '') || (name.value === '') || (password.value === '')) {
          alert('Please input E-Mail address and name, password.', 'Caution!');
          return
        }
        if (confirm.value === '') {
          alert('Please input password for confirm.', 'Caution!');
          return
        }
        if (password.value !== confirm.value) {
          alert('Password and confirm password is not match.', 'Caution!');
          return
        }
        let fData = new FormData();
        fData.append('email', email.value);
        fData.append('name', name.value);
        fData.append('password', password.value);
        
        fetch("{{url_for('auth.register')}}", {
          method: 'POST',
          headers: {},
          body: fData
        }).then(response => {
          if (response.url.split('/').pop() === "{{url_for('auth.login')}}".split('/').pop()) {
            window.location.href = response.url;
            alert('Registering your account is completed!', 'Completed!');
          }
          else if (response.url.split('/').pop() === "{{url_for('auth.register')}}".split('/').pop()) {
            alert('Your e-mail is already registered!', 'Already registered!');
          }
          else {
            alert('Occuring some error on register process.', 'Error is happen!');
          }
        }).catch(error => {
          alert('Occuring some error on register process.', 'Error is happen!');
        });
      }
    </script>
  </body>
</html>

app/templates/video_editor.html
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Main</title>
  </head>
  <body>
    <div style="text-align:right;">
      <p>{{name}}</p>
      <button onclick="window.location.href='{{url_for('auth.logout')}}';">Log out</button>
     </div>
    <div>
      <div>
        <form id="uploadMp4">
          <span>Upload mp4 file: </span>
          <input type="file" name="file" accept=".mp4">
        </form>
        <button onclick="onFetchUpload();">upload</button>
        <p id="uploadResult"></p>
      </div>
    </div>
    <script>
      function onFetchUpload () {
        const uploadForm = document.getElementById('uploadMp4');
        const fData = new FormData(uploadForm);
        fetch(`{{url_for('editor.upload_file')}}`, {method:'POST', body: fData}).then( response => {
          response.status === 200 ? response.json() : Promise.reject(response.status);
          const result = document.getElementById('uploadResult');
          if (result) result.innerHTML = response.status.toString();
          console.log(response.status.toString());
        });
      }
    </script>
  </body>
</html>